[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.black]
line-length = 79
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.mypy]
implicit_optional = true  # No longer a default; we should consider disabling this!

[[tool.mypy.overrides]]
module = "fsspec"
ignore_missing_imports = true

# TODO
[[tool.mypy.overrides]]
module = "airpot"
ignore_missing_imports = true

# TODO
[[tool.mypy.overrides]]
module = "cortado"
ignore_missing_imports = true

# TODO
[[tool.mypy.overrides]]
module = "wheely.mammoth"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "wheely.mammoth.utils"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "wheely.mammoth.parsers"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "wheely.mammoth.proteins"
ignore_missing_imports = true
