name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#        with:
#          python-version: "3.8"
      - run: pip install .[dev,toml]
      - uses: psf/black@stable
      - name: mypy
        uses: tsuyoshicho/action-mypy@v3.9.3
        with:
          workdir: scry/
          reporter: github-pr-check
          level: error
          tool_name: mypy
