name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
      - name: mypy
        uses: tsuyoshicho/action-mypy@v3.9.3
        with:
          reporter: github-pr-check
          level: error
          tool_name: mypy
