name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: [self-hosted, X64]
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#        with:
#          python-version: "3.8"
      - run: |
          pip config unset global.index-url || true  # Ensure we don't have old CodeArtifact creds in pip config
          pip install 'awscli>=1.18.83'
          aws codeartifact login --tool pip --repository seer_ds --domain seer --domain-owner 718843040700 --region us-west-2
          pip install '.[dev]'
      - uses: psf/black@stable
      - name: mypy
        uses: tsuyoshicho/action-mypy@v3.9.3
        with:
          target: scry/
          reporter: github-pr-check
          level: error
          tool_name: mypy
